version: '3.7'
services:
  django:
    restart: always
    build: ./django
    expose:
      - "3031"
    depends_on:
      - postgres
    command: bash -c "cd cmssite && gunicorn cmssite.wsgi -b 0.0.0.0:3031"
    volumes:
      - "./django:/opt/apps" # 2019/09/28 kurawo add
      - "./puput:/usr/local/lib/python3.7/site-packages/puput" # 2019/10/19 kurawo add
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "./django/cmssite/static:/opt/apps/static/" # 2019/10/20 kurawo add
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: hogemojahogemoja

volumes:
  dbdata:
