kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: sample
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/tmp/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sample
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
